{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "annual-printing",
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/ray/autoscaler/_private/cli_logger.py:61: FutureWarning: Not all Ray CLI dependencies were found. In Ray 1.4+, the Ray CLI, autoscaler, and dashboard will only be usable via `pip install 'ray[default]'`. Please update your install command.\n",
      "  \"update your install command.\", FutureWarning)\n",
      "/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/gym/logger.py:30: UserWarning: \u001b[33mWARN: Box bound precision lowered by casting to float32\u001b[0m\n",
      "  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))\n"
     ]
    }
   ],
   "source": [
    "from model import DQN\n",
    "import os\n",
    "import minerl\n",
    "import gym\n",
    "import torch\n",
    "import torch.nn.functional as F\n",
    "import torch.optim as optim\n",
    "import ray\n",
    "import pandas as pd\n",
    "import gc\n",
    "import asyncio\n",
    "from _collections import deque\n",
    "from utils import *\n",
    "import random\n",
    "import copy\n",
    "\n",
    "def learner_append_sample(memory, model, target_model, state, action, reward, next_state, done):\n",
    "    # Caluclating Priority (TD Error)\n",
    "    target = model(state.float()).data.cpu()\n",
    "    old_val = target[0][action].cpu()\n",
    "    target_val = target_model(next_state.float()).data.cpu()\n",
    "    if done:\n",
    "        target[0][action] = reward\n",
    "    else:\n",
    "        target[0][action] = reward + 0.99 * torch.max(target_val)\n",
    "\n",
    "    error = abs(old_val - target[0][action])\n",
    "    error = error.cpu()\n",
    "    memory.add.remote(error, [state, action, reward, next_state, done])\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "express-reservation",
   "metadata": {},
   "outputs": [],
   "source": [
    "@ray.remote\n",
    "class Actor:\n",
    "    def __init__(self, learner, actor_idx, startEpsilon, endEpsilon, paramServer, action_size):\n",
    "        # environment initialization\n",
    "        self.actor_idx = actor_idx\n",
    "        self.env = gym.make(\"MineRLTreechop-v0\")\n",
    "        self.port_number = int(\"12340\") + actor_idx\n",
    "        print(\"actor environment %d initialize successfully\" % self.actor_idx)\n",
    "        self.env.make_interactive(port=self.port_number, realtime=False)\n",
    "        self.shared_network_cpu = ray.get(learner.get_network.remote())\n",
    "        # self.shared_memory = ray.get(shared_memory_id)\n",
    "        # print(\"shared memory assign successfully\")\n",
    "        \n",
    "        # network initalization\n",
    "        self.actor_network = DQN(action_size).cpu()\n",
    "        self.actor_target_network = DQN(action_size).cpu()\n",
    "        self.actor_network.load_state_dict(self.shared_network_cpu.state_dict())\n",
    "        self.actor_target_network.load_state_dict(self.actor_network.state_dict())\n",
    "        print(\"actor network %d initialize successfully\" % self.actor_idx)\n",
    "\n",
    "        self.initialized = False\n",
    "        self.epi_counter = 0\n",
    "        # exploring info\n",
    "        self.startEpsilon = startEpsilon\n",
    "        self.endEpsilon = endEpsilon\n",
    "        self.max_episodes = 100\n",
    "\n",
    "        self.paramServer = paramServer\n",
    "        \n",
    "    \n",
    "    # 1. 네트워크 파라미터 복사\n",
    "    # 2. 환경 탐험 (초기화, 행동)\n",
    "    # 3. 로컬버퍼에 저장\n",
    "    # 4. priority 계산\n",
    "    # 5. 글로벌 버퍼에 저장\n",
    "    # 6. 주기적으로 네트워크 업데이트\n",
    "\n",
    "    def get_initialized(self):\n",
    "        return self.initialized\n",
    "\n",
    "    def get_counter(self):\n",
    "        return self.epi_counter\n",
    "\n",
    "    # 각 환경 인스턴스에서 각 엡실론에 따라 탐험을 진행한다.\n",
    "    # 탐험 과정에서 local buffer에 transition들을 저장한다.\n",
    "    # local buffer의 개수가 특정 개수 이상이면 global buffer에 추가해준다.\n",
    "\n",
    "    def explore(self, learner, shared_memory):\n",
    "        \n",
    "        self.initialized = True\n",
    "        stepDrop = (self.startEpsilon - self.endEpsilon) / self.max_episodes\n",
    "        epsilon = self.startEpsilon\n",
    "        total_steps = 0\n",
    "        \n",
    "        episodes = [x for x in range(self.max_episodes)]\n",
    "        train_stats = pd.DataFrame(index=episodes, columns=['rewards'])\n",
    "        \n",
    "        for num_epi in range(self.max_episodes):\n",
    "            obs = self.env.reset()\n",
    "            state = converter(obs).cpu().float()\n",
    "            done = False\n",
    "            total_reward = 0\n",
    "            steps = 0\n",
    "            if (epsilon > self.endEpsilon):\n",
    "                epsilon -= stepDrop\n",
    "                \n",
    "            while not done:\n",
    "                steps += 1\n",
    "                total_steps += 1\n",
    "                a_out = self.actor_network.sample_action(state, epsilon)\n",
    "                action_index = a_out\n",
    "                action = make_action2(self.env, action_index)\n",
    "                obs_prime, reward, done, info = self.env.step(action)\n",
    "                total_reward += reward\n",
    "                state_prime = converter(obs_prime)\n",
    "\n",
    "                self.actor_append_sample(shared_memory, self.actor_network, self.actor_target_network, \\\n",
    "                                       state, action_index, reward, state_prime, done)\n",
    "\n",
    "                state = state_prime.float().cpu()\n",
    "                if done:\n",
    "                    break\n",
    "                    \n",
    "            # pandas로 리워드 기록하기\n",
    "            print(\"%d episode is done\" % num_epi)\n",
    "            print(\"total rewards : %d \" % total_reward)\n",
    "            train_stats.loc[num_epi]['rewards'] = total_reward\n",
    "            train_stats.to_csv('train_stat_minerl_agent {}.csv'.format(str(self.actor_idx)))\n",
    "            \n",
    "  \n",
    "            self.pull_parameters(learner) \n",
    "            print(\"actor network is updated \")\n",
    "            print(\"actor target_network is updated\")\n",
    "    \n",
    "    def pull_parameters(self, learner):\n",
    "        ray.get(self.paramServer.pull_parameters.remote(learner)) \n",
    "        policy_params, target_params = ray.get(self.paramServer.return_parameters.remote())\n",
    "        self.actor_network.load_state_dict(policy_params)\n",
    "        self.actor_target_network.load_state_dict(target_params)\n",
    "        \n",
    "    def env_close(self):\n",
    "        self.env.close()        \n",
    "\n",
    "    def actor_append_sample(self, memory, model, target_model, state, action, reward, next_state, done):\n",
    "        # Caluclating Priority (TD Error)\n",
    "        target = model(state.float()).data.cpu()\n",
    "        old_val = target[0][action].cpu()\n",
    "        target_val = target_model(next_state.float()).data.cpu()\n",
    "        if done:\n",
    "            target[0][action] = reward\n",
    "        else:\n",
    "            target[0][action] = reward + 0.99 * torch.max(target_val)\n",
    "\n",
    "        error = abs(old_val - target[0][action])\n",
    "        error = error.cpu()\n",
    "        memory.add.remote(error, [state, action, reward, next_state, done])\n",
    "\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "clean-university",
   "metadata": {},
   "outputs": [],
   "source": [
    "@ray.remote\n",
    "class ParameterServer:\n",
    "    def __init__(self, action_size):\n",
    "        self.policy_params = DQN(action_size).state_dict()\n",
    "        self.target_params = DQN(action_size).state_dict()\n",
    "    \n",
    "    def pull_parameters(self, learner):\n",
    "        learner.push_parameters.remote(self.policy_params, self.target_params)\n",
    "        return 1\n",
    "    \n",
    "    def return_parameters(self):\n",
    "        return self.policy_params, self.target_params\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "correct-pride",
   "metadata": {},
   "outputs": [],
   "source": [
    "@ray.remote(num_gpus=1)\n",
    "class Learner:\n",
    "    def __init__(self, network, batch_size, paramServer, action_size):\n",
    "        self.learner_network = DQN(action_size).cuda().float()\n",
    "        self.learner_target_network = DQN(action_size).cuda().float()\n",
    "        self.learner_network.load_state_dict(network.state_dict())\n",
    "        self.learner_target_network.load_state_dict(network.state_dict())\n",
    "        self.shared_network = DQN(action_size).cpu()\n",
    "        self.shared_target_network = DQN(action_size).cpu()\n",
    "        \n",
    "        self.paramServer = paramServer\n",
    "        \n",
    "        self.count = 0\n",
    "        self.batch_size = batch_size\n",
    "        self.max_counts= 100000\n",
    "\n",
    "    # 1. sampling\n",
    "    # 2. calculate gradient\n",
    "    # 3. weight update\n",
    "    # 4. compute priorities\n",
    "    # 5. priorities of buffer update\n",
    "    # 6. remove old memory\n",
    "    \n",
    "    def push_parameters(self, server_policy_params, server_target_params):\n",
    "        self.shared_network.load_state_dict(self.learner_network.state_dict())\n",
    "        self.shared_target_network.load_state_dict(self.learner_target_network.state_dict())\n",
    "        policy_net_params = self.shared_network.state_dict()\n",
    "        target_net_params = self.shared_target_network.state_dict()\n",
    "        server_policy_params = policy_net_params\n",
    "        server_target_params = target_net_params\n",
    "        \n",
    "    def count(self):\n",
    "        return self.count\n",
    "    \n",
    "    def get_network(self):\n",
    "        self.shared_network.load_state_dict(self.learner_network.state_dict())\n",
    "        print(\"return learner network\")\n",
    "        return self.shared_network\n",
    "    \n",
    "    def get_target_network(self):\n",
    "        self.shared_target_network.load_state_dict(self.learner_target_network.state_dict())\n",
    "        return self.shared_target_network\n",
    "\n",
    "    def update_network(self, memory, batch_size, optimizer):\n",
    "        print(\"started\")\n",
    "\n",
    "        \n",
    "        counts = [x for x in range(self.max_counts)]\n",
    "        train_stats = pd.DataFrame(index=counts, columns=['loss'])\n",
    "        while(self.count < 10000000):\n",
    "            agent_batch, agent_idxs, agent_weights = ray.get(memory.sample.remote(batch_size))\n",
    "            state_list = []\n",
    "            action_list = []\n",
    "            reward_list = []\n",
    "            next_state_list = []\n",
    "            done_mask_list = []\n",
    "\n",
    "            #print(\"agent batch len : {} \".format(str(len(agent_batch))))\n",
    "            for agent_transition in agent_batch:\n",
    "                s, a, r, s_prime, done_mask = agent_transition\n",
    "                state_list.append(s)\n",
    "                action_list.append([a])\n",
    "                reward_list.append([r])\n",
    "                next_state_list.append(s_prime)\n",
    "                done_mask_list.append([done_mask])\n",
    "\n",
    "            s = torch.stack(state_list).float().cuda()\n",
    "            a = torch.tensor(action_list, dtype=torch.int64).cuda()\n",
    "            r = torch.tensor(reward_list).cuda()\n",
    "            s_prime = torch.stack(next_state_list).float().cuda()\n",
    "            done_mask = torch.tensor(done_mask_list).float().cuda()\n",
    "\n",
    "            q_vals = self.learner_network(s)\n",
    "            state_action_values = q_vals.gather(1, a)\n",
    "\n",
    "            # comparing the q values to the values expected using the next states and reward\n",
    "            next_state_values = self.learner_target_network(s_prime).max(1)[0].unsqueeze(1)\n",
    "            target = r + (next_state_values * gamma * done_mask)\n",
    "\n",
    "            # calculating the q loss, n-step return lossm supervised_loss\n",
    "            is_weights = torch.FloatTensor(agent_weights).to(device)\n",
    "            q_loss = (is_weights * F.mse_loss(state_action_values, target)).mean()\n",
    "            #supervised_loss = margin_loss(q_vals, a, 1, 1)\n",
    "\n",
    "            loss = q_loss #+ supervised_loss\n",
    "            errors = torch.abs(state_action_values - target).data.cpu().detach()\n",
    "            errors = errors.numpy()\n",
    "            # update priority\n",
    "            for i in range(batch_size):\n",
    "                idx = agent_idxs[i]\n",
    "                memory.update.remote(idx, errors[i])\n",
    "\n",
    "            train_stats.loc[self.count ]['loss'] = float(loss.item())\n",
    "            train_stats.to_csv('train_stat_minerl_learner.csv')\n",
    "\n",
    "            # optimization step and logging\n",
    "            optimizer.zero_grad()\n",
    "            loss.backward()\n",
    "            optimizer.step()\n",
    "            self.count +=1\n",
    "            if(self.count % 50 == 0 and self.count != 0):\n",
    "                self.learner_target_network.load_state_dict(self.learner_network.state_dict())\n",
    "                print(\"Count : {} leaner_target_network updated\".format(self.count))\n",
    "                \n",
    "            if(self.count % 10 == 0 and self.count!= 0):\n",
    "                print(\"Count : {} leaner_network updated\".format(self.count))\n",
    "                torch.save(self.learner_network.state_dict(),\"apex_dqfd_learner_9action.pth\")\n",
    "                print(\"learner model saved\")\n",
    "                \n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "dirty-summary",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-06-10 18:08:05,470\tINFO services.py:1269 -- View the Ray dashboard at \u001b[1m\u001b[32mhttp://127.0.0.1:8265\u001b[39m\u001b[22m\n"
     ]
    }
   ],
   "source": [
    "ray.init()\n",
    "\n",
    "#하이퍼 파라미터\n",
    "learning_rate = 0.0001\n",
    "gamma = 0.999\n",
    "buffer_limit = 50000\n",
    "L1 = 0.9\n",
    "device = torch.device(\"cuda:0\" if torch.cuda.is_available() else \"cpu\")\n",
    "\n",
    "root_path = os.curdir\n",
    "model_path = root_path + '/dqn_model/'\n",
    "action_size = 9"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "certain-savage",
   "metadata": {},
   "outputs": [],
   "source": [
    "policy_net = DQN(action_size).cuda()\n",
    "target_net = DQN(action_size).cuda()\n",
    "target_net.load_state_dict(policy_net.state_dict())\n",
    "memory = Memory.remote(40000)\n",
    "optimizer = optim.Adam(policy_net.parameters(), lr=learning_rate, weight_decay=1e-5)\n",
    "\n",
    "# Copy network params from pretrained Agent\n",
    "#model_path = './dqn_model/apex_dqfd_learner.pth'\n",
    "#policy_net.load_state_dict(torch.load(model_path, map_location='cuda:0'))\n",
    "#target_net.load_state_dict(policy_net.state_dict())\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "organizational-relative",
   "metadata": {},
   "outputs": [],
   "source": [
    "params_server = ParameterServer.remote(action_size)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "macro-criticism",
   "metadata": {},
   "outputs": [],
   "source": [
    "# learner network initialzation\n",
    "batch_size = 512\n",
    "\n",
    "learner = Learner.remote(policy_net, batch_size, params_server, action_size)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "fundamental-heart",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=7999)\u001b[0m Memory is initialized\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m /home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/gym/logger.py:30: UserWarning: \u001b[33mWARN: Box bound precision lowered by casting to float32\u001b[0m\n",
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m   warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))\n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m /home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/gym/logger.py:30: UserWarning: \u001b[33mWARN: Box bound precision lowered by casting to float32\u001b[0m\n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m   warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=7996)\u001b[0m return learner network\n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m actor environment 0 initialize successfully\n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m actor network 0 initialize successfully\n",
      "\u001b[2m\u001b[36m(pid=7996)\u001b[0m return learner network\n",
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m actor environment 1 initialize successfully\n",
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m actor network 1 initialize successfully\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-06-11 15:05:15,184\tWARNING worker.py:1115 -- The autoscaler failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/ray/_private/monitor.py\", line 284, in run\n",
      "    self._run()\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/ray/_private/monitor.py\", line 175, in _run\n",
      "    self.update_load_metrics()\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/ray/_private/monitor.py\", line 140, in update_load_metrics\n",
      "    request, timeout=4)\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/grpc/_channel.py\", line 923, in __call__\n",
      "    return _end_unary_response_blocking(state, call, False, None)\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/grpc/_channel.py\", line 826, in _end_unary_response_blocking\n",
      "    raise _InactiveRpcError(state)\n",
      "grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.DEADLINE_EXCEEDED\n",
      "\tdetails = \"Deadline Exceeded\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1623391508.612347697\",\"description\":\"Error received from peer ipv4:192.168.0.22:43257\",\"file\":\"src/core/lib/surface/call.cc\",\"file_line\":1067,\"grpc_message\":\"Deadline Exceeded\",\"grpc_status\":4}\"\n",
      ">\n",
      "\n"
     ]
    }
   ],
   "source": [
    "# actor network, environments initialization\n",
    "# Generating each own instances\n",
    "\n",
    "actor1 = Actor.remote(learner, 0, 0.1, 0.01, params_server, action_size)\n",
    "actor2 = Actor.remote(learner, 1, 0.05, 0.01, params_server,action_size)\n",
    "#actor3 = Actor.remote(learner, 2, 0.1, 0.01, params_server, action_size)\n",
    "actor_list = [actor1, actor2]\n",
    "#actor_list = [actor1, actor2, actor3]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "executed-convergence",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m MineRL agent is public, connect on port 12341 with Minecraft 1.11\n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m MineRL agent is public, connect on port 12340 with Minecraft 1.11\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m 0 episode is done\n",
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m total rewards : 0 \n",
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m actor network is updated \n",
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m actor target_network is updated\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-06-11 15:13:48,971\tERROR worker.py:1056 -- Possible unhandled error from worker: \u001b[36mray::Learner.push_parameters()\u001b[39m (pid=7996, ip=192.168.0.22)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"<ipython-input-4-7598620ccee7>\", line 25, in push_parameters\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 1052, in load_state_dict\n",
      "    self.__class__.__name__, \"\\n\\t\".join(error_msgs)))\n",
      "RuntimeError: Error(s) in loading state_dict for DQN:\n",
      "\tWhile copying the parameter named \"conv1.weight\", whose dimensions in the model are torch.Size([32, 3, 8, 8]) and whose dimensions in the checkpoint are torch.Size([32, 3, 8, 8]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv1.bias\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.weight\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.bias\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.running_mean\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.running_var\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv2.weight\", whose dimensions in the model are torch.Size([64, 32, 4, 4]) and whose dimensions in the checkpoint are torch.Size([64, 32, 4, 4]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv2.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.weight\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.running_mean\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.running_var\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv3.weight\", whose dimensions in the model are torch.Size([64, 64, 3, 3]) and whose dimensions in the checkpoint are torch.Size([64, 64, 3, 3]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv3.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.weight\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.running_mean\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.running_var\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"head.weight\", whose dimensions in the model are torch.Size([9, 1024]) and whose dimensions in the checkpoint are torch.Size([9, 1024]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"head.bias\", whose dimensions in the model are torch.Size([9]) and whose dimensions in the checkpoint are torch.Size([9]), an exception occurred : ('CUDA error: unspecified launch failure',).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m 0 episode is done\n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m total rewards : 0 \n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m actor network is updated \n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m actor target_network is updated\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m MineRL agent is public, connect on port 12341 with Minecraft 1.11\n",
      "2021-06-11 15:14:05,902\tERROR worker.py:1056 -- Possible unhandled error from worker: \u001b[36mray::Learner.push_parameters()\u001b[39m (pid=7996, ip=192.168.0.22)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"<ipython-input-4-7598620ccee7>\", line 25, in push_parameters\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 1052, in load_state_dict\n",
      "    self.__class__.__name__, \"\\n\\t\".join(error_msgs)))\n",
      "RuntimeError: Error(s) in loading state_dict for DQN:\n",
      "\tWhile copying the parameter named \"conv1.weight\", whose dimensions in the model are torch.Size([32, 3, 8, 8]) and whose dimensions in the checkpoint are torch.Size([32, 3, 8, 8]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv1.bias\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.weight\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.bias\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.running_mean\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.running_var\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv2.weight\", whose dimensions in the model are torch.Size([64, 32, 4, 4]) and whose dimensions in the checkpoint are torch.Size([64, 32, 4, 4]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv2.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.weight\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.running_mean\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.running_var\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv3.weight\", whose dimensions in the model are torch.Size([64, 64, 3, 3]) and whose dimensions in the checkpoint are torch.Size([64, 64, 3, 3]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv3.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.weight\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.running_mean\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.running_var\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"head.weight\", whose dimensions in the model are torch.Size([9, 1024]) and whose dimensions in the checkpoint are torch.Size([9, 1024]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"head.bias\", whose dimensions in the model are torch.Size([9]) and whose dimensions in the checkpoint are torch.Size([9]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m MineRL agent is public, connect on port 12340 with Minecraft 1.11\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m 1 episode is done\n",
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m total rewards : 2 \n",
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m actor network is updated \n",
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m actor target_network is updated\n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m 1 episode is done\n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m total rewards : 5 \n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m actor network is updated \n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m actor target_network is updated\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-06-11 15:15:50,398\tERROR worker.py:1056 -- Possible unhandled error from worker: \u001b[36mray::Learner.push_parameters()\u001b[39m (pid=7996, ip=192.168.0.22)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"<ipython-input-4-7598620ccee7>\", line 25, in push_parameters\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 1052, in load_state_dict\n",
      "    self.__class__.__name__, \"\\n\\t\".join(error_msgs)))\n",
      "RuntimeError: Error(s) in loading state_dict for DQN:\n",
      "\tWhile copying the parameter named \"conv1.weight\", whose dimensions in the model are torch.Size([32, 3, 8, 8]) and whose dimensions in the checkpoint are torch.Size([32, 3, 8, 8]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv1.bias\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.weight\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.bias\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.running_mean\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.running_var\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv2.weight\", whose dimensions in the model are torch.Size([64, 32, 4, 4]) and whose dimensions in the checkpoint are torch.Size([64, 32, 4, 4]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv2.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.weight\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.running_mean\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.running_var\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv3.weight\", whose dimensions in the model are torch.Size([64, 64, 3, 3]) and whose dimensions in the checkpoint are torch.Size([64, 64, 3, 3]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv3.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.weight\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.running_mean\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.running_var\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"head.weight\", whose dimensions in the model are torch.Size([9, 1024]) and whose dimensions in the checkpoint are torch.Size([9, 1024]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"head.bias\", whose dimensions in the model are torch.Size([9]) and whose dimensions in the checkpoint are torch.Size([9]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "2021-06-11 15:15:54,399\tERROR worker.py:1056 -- Possible unhandled error from worker: \u001b[36mray::Learner.push_parameters()\u001b[39m (pid=7996, ip=192.168.0.22)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"<ipython-input-4-7598620ccee7>\", line 25, in push_parameters\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 1052, in load_state_dict\n",
      "    self.__class__.__name__, \"\\n\\t\".join(error_msgs)))\n",
      "RuntimeError: Error(s) in loading state_dict for DQN:\n",
      "\tWhile copying the parameter named \"conv1.weight\", whose dimensions in the model are torch.Size([32, 3, 8, 8]) and whose dimensions in the checkpoint are torch.Size([32, 3, 8, 8]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv1.bias\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.weight\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.bias\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.running_mean\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.running_var\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv2.weight\", whose dimensions in the model are torch.Size([64, 32, 4, 4]) and whose dimensions in the checkpoint are torch.Size([64, 32, 4, 4]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv2.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.weight\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.running_mean\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.running_var\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv3.weight\", whose dimensions in the model are torch.Size([64, 64, 3, 3]) and whose dimensions in the checkpoint are torch.Size([64, 64, 3, 3]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv3.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.weight\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.running_mean\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.running_var\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"head.weight\", whose dimensions in the model are torch.Size([9, 1024]) and whose dimensions in the checkpoint are torch.Size([9, 1024]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"head.bias\", whose dimensions in the model are torch.Size([9]) and whose dimensions in the checkpoint are torch.Size([9]), an exception occurred : ('CUDA error: unspecified launch failure',).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m MineRL agent is public, connect on port 12341 with Minecraft 1.11\n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m MineRL agent is public, connect on port 12340 with Minecraft 1.11\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m 2 episode is done\n",
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m total rewards : 1 \n",
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m actor network is updated \n",
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m actor target_network is updated\n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m 2 episode is done\n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m total rewards : 7 \n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m actor network is updated \n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m actor target_network is updated\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-06-11 15:17:29,913\tERROR worker.py:1056 -- Possible unhandled error from worker: \u001b[36mray::Learner.push_parameters()\u001b[39m (pid=7996, ip=192.168.0.22)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"<ipython-input-4-7598620ccee7>\", line 25, in push_parameters\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 1052, in load_state_dict\n",
      "    self.__class__.__name__, \"\\n\\t\".join(error_msgs)))\n",
      "RuntimeError: Error(s) in loading state_dict for DQN:\n",
      "\tWhile copying the parameter named \"conv1.weight\", whose dimensions in the model are torch.Size([32, 3, 8, 8]) and whose dimensions in the checkpoint are torch.Size([32, 3, 8, 8]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv1.bias\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.weight\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.bias\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.running_mean\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.running_var\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv2.weight\", whose dimensions in the model are torch.Size([64, 32, 4, 4]) and whose dimensions in the checkpoint are torch.Size([64, 32, 4, 4]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv2.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.weight\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.running_mean\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.running_var\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv3.weight\", whose dimensions in the model are torch.Size([64, 64, 3, 3]) and whose dimensions in the checkpoint are torch.Size([64, 64, 3, 3]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv3.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.weight\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.running_mean\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.running_var\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"head.weight\", whose dimensions in the model are torch.Size([9, 1024]) and whose dimensions in the checkpoint are torch.Size([9, 1024]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"head.bias\", whose dimensions in the model are torch.Size([9]) and whose dimensions in the checkpoint are torch.Size([9]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "2021-06-11 15:17:32,914\tERROR worker.py:1056 -- Possible unhandled error from worker: \u001b[36mray::Learner.push_parameters()\u001b[39m (pid=7996, ip=192.168.0.22)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"<ipython-input-4-7598620ccee7>\", line 25, in push_parameters\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 1052, in load_state_dict\n",
      "    self.__class__.__name__, \"\\n\\t\".join(error_msgs)))\n",
      "RuntimeError: Error(s) in loading state_dict for DQN:\n",
      "\tWhile copying the parameter named \"conv1.weight\", whose dimensions in the model are torch.Size([32, 3, 8, 8]) and whose dimensions in the checkpoint are torch.Size([32, 3, 8, 8]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv1.bias\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.weight\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.bias\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.running_mean\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.running_var\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv2.weight\", whose dimensions in the model are torch.Size([64, 32, 4, 4]) and whose dimensions in the checkpoint are torch.Size([64, 32, 4, 4]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv2.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.weight\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.running_mean\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.running_var\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv3.weight\", whose dimensions in the model are torch.Size([64, 64, 3, 3]) and whose dimensions in the checkpoint are torch.Size([64, 64, 3, 3]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv3.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.weight\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.running_mean\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.running_var\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"head.weight\", whose dimensions in the model are torch.Size([9, 1024]) and whose dimensions in the checkpoint are torch.Size([9, 1024]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"head.bias\", whose dimensions in the model are torch.Size([9]) and whose dimensions in the checkpoint are torch.Size([9]), an exception occurred : ('CUDA error: unspecified launch failure',).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m MineRL agent is public, connect on port 12341 with Minecraft 1.11\n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m MineRL agent is public, connect on port 12340 with Minecraft 1.11\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m 3 episode is done\n",
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m total rewards : 5 \n",
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m actor network is updated \n",
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m actor target_network is updated\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-06-11 15:19:11,776\tERROR worker.py:1056 -- Possible unhandled error from worker: \u001b[36mray::Learner.push_parameters()\u001b[39m (pid=7996, ip=192.168.0.22)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"<ipython-input-4-7598620ccee7>\", line 25, in push_parameters\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 1052, in load_state_dict\n",
      "    self.__class__.__name__, \"\\n\\t\".join(error_msgs)))\n",
      "RuntimeError: Error(s) in loading state_dict for DQN:\n",
      "\tWhile copying the parameter named \"conv1.weight\", whose dimensions in the model are torch.Size([32, 3, 8, 8]) and whose dimensions in the checkpoint are torch.Size([32, 3, 8, 8]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv1.bias\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.weight\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.bias\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.running_mean\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.running_var\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv2.weight\", whose dimensions in the model are torch.Size([64, 32, 4, 4]) and whose dimensions in the checkpoint are torch.Size([64, 32, 4, 4]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv2.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.weight\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.running_mean\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.running_var\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv3.weight\", whose dimensions in the model are torch.Size([64, 64, 3, 3]) and whose dimensions in the checkpoint are torch.Size([64, 64, 3, 3]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv3.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.weight\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.running_mean\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.running_var\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"head.weight\", whose dimensions in the model are torch.Size([9, 1024]) and whose dimensions in the checkpoint are torch.Size([9, 1024]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"head.bias\", whose dimensions in the model are torch.Size([9]) and whose dimensions in the checkpoint are torch.Size([9]), an exception occurred : ('CUDA error: unspecified launch failure',).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m 3 episode is done\n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m total rewards : 4 \n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m actor network is updated \n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m actor target_network is updated\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-06-11 15:19:17,342\tERROR worker.py:1056 -- Possible unhandled error from worker: \u001b[36mray::Learner.push_parameters()\u001b[39m (pid=7996, ip=192.168.0.22)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"<ipython-input-4-7598620ccee7>\", line 25, in push_parameters\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 1052, in load_state_dict\n",
      "    self.__class__.__name__, \"\\n\\t\".join(error_msgs)))\n",
      "RuntimeError: Error(s) in loading state_dict for DQN:\n",
      "\tWhile copying the parameter named \"conv1.weight\", whose dimensions in the model are torch.Size([32, 3, 8, 8]) and whose dimensions in the checkpoint are torch.Size([32, 3, 8, 8]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv1.bias\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.weight\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.bias\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.running_mean\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.running_var\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv2.weight\", whose dimensions in the model are torch.Size([64, 32, 4, 4]) and whose dimensions in the checkpoint are torch.Size([64, 32, 4, 4]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv2.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.weight\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.running_mean\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.running_var\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv3.weight\", whose dimensions in the model are torch.Size([64, 64, 3, 3]) and whose dimensions in the checkpoint are torch.Size([64, 64, 3, 3]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv3.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.weight\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.running_mean\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.running_var\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"head.weight\", whose dimensions in the model are torch.Size([9, 1024]) and whose dimensions in the checkpoint are torch.Size([9, 1024]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"head.bias\", whose dimensions in the model are torch.Size([9]) and whose dimensions in the checkpoint are torch.Size([9]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m MineRL agent is public, connect on port 12341 with Minecraft 1.11\n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m MineRL agent is public, connect on port 12340 with Minecraft 1.11\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m 4 episode is done\n",
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m total rewards : 2 \n",
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m actor network is updated \n",
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m actor target_network is updated\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-06-11 15:20:48,489\tERROR worker.py:1056 -- Possible unhandled error from worker: \u001b[36mray::Learner.push_parameters()\u001b[39m (pid=7996, ip=192.168.0.22)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"<ipython-input-4-7598620ccee7>\", line 25, in push_parameters\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 1052, in load_state_dict\n",
      "    self.__class__.__name__, \"\\n\\t\".join(error_msgs)))\n",
      "RuntimeError: Error(s) in loading state_dict for DQN:\n",
      "\tWhile copying the parameter named \"conv1.weight\", whose dimensions in the model are torch.Size([32, 3, 8, 8]) and whose dimensions in the checkpoint are torch.Size([32, 3, 8, 8]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv1.bias\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.weight\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.bias\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.running_mean\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.running_var\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv2.weight\", whose dimensions in the model are torch.Size([64, 32, 4, 4]) and whose dimensions in the checkpoint are torch.Size([64, 32, 4, 4]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv2.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.weight\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.running_mean\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.running_var\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv3.weight\", whose dimensions in the model are torch.Size([64, 64, 3, 3]) and whose dimensions in the checkpoint are torch.Size([64, 64, 3, 3]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv3.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.weight\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.running_mean\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.running_var\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"head.weight\", whose dimensions in the model are torch.Size([9, 1024]) and whose dimensions in the checkpoint are torch.Size([9, 1024]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"head.bias\", whose dimensions in the model are torch.Size([9]) and whose dimensions in the checkpoint are torch.Size([9]), an exception occurred : ('CUDA error: unspecified launch failure',).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m 4 episode is done\n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m total rewards : 0 \n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m actor network is updated \n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m actor target_network is updated\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-06-11 15:20:54,216\tERROR worker.py:1056 -- Possible unhandled error from worker: \u001b[36mray::Learner.push_parameters()\u001b[39m (pid=7996, ip=192.168.0.22)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"<ipython-input-4-7598620ccee7>\", line 25, in push_parameters\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 1052, in load_state_dict\n",
      "    self.__class__.__name__, \"\\n\\t\".join(error_msgs)))\n",
      "RuntimeError: Error(s) in loading state_dict for DQN:\n",
      "\tWhile copying the parameter named \"conv1.weight\", whose dimensions in the model are torch.Size([32, 3, 8, 8]) and whose dimensions in the checkpoint are torch.Size([32, 3, 8, 8]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv1.bias\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.weight\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.bias\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.running_mean\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.running_var\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv2.weight\", whose dimensions in the model are torch.Size([64, 32, 4, 4]) and whose dimensions in the checkpoint are torch.Size([64, 32, 4, 4]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv2.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.weight\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.running_mean\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.running_var\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv3.weight\", whose dimensions in the model are torch.Size([64, 64, 3, 3]) and whose dimensions in the checkpoint are torch.Size([64, 64, 3, 3]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv3.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.weight\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.running_mean\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.running_var\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"head.weight\", whose dimensions in the model are torch.Size([9, 1024]) and whose dimensions in the checkpoint are torch.Size([9, 1024]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"head.bias\", whose dimensions in the model are torch.Size([9]) and whose dimensions in the checkpoint are torch.Size([9]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m MineRL agent is public, connect on port 12341 with Minecraft 1.11\n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m MineRL agent is public, connect on port 12340 with Minecraft 1.11\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m 5 episode is done\n",
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m total rewards : 0 \n",
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m actor network is updated \n",
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m actor target_network is updated\n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m 5 episode is done\n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m total rewards : 5 \n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m actor network is updated \n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m actor target_network is updated\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-06-11 15:22:31,307\tERROR worker.py:1056 -- Possible unhandled error from worker: \u001b[36mray::Learner.push_parameters()\u001b[39m (pid=7996, ip=192.168.0.22)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"<ipython-input-4-7598620ccee7>\", line 25, in push_parameters\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 1052, in load_state_dict\n",
      "    self.__class__.__name__, \"\\n\\t\".join(error_msgs)))\n",
      "RuntimeError: Error(s) in loading state_dict for DQN:\n",
      "\tWhile copying the parameter named \"conv1.weight\", whose dimensions in the model are torch.Size([32, 3, 8, 8]) and whose dimensions in the checkpoint are torch.Size([32, 3, 8, 8]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv1.bias\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.weight\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.bias\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.running_mean\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.running_var\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv2.weight\", whose dimensions in the model are torch.Size([64, 32, 4, 4]) and whose dimensions in the checkpoint are torch.Size([64, 32, 4, 4]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv2.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.weight\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.running_mean\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.running_var\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv3.weight\", whose dimensions in the model are torch.Size([64, 64, 3, 3]) and whose dimensions in the checkpoint are torch.Size([64, 64, 3, 3]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv3.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.weight\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.running_mean\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.running_var\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"head.weight\", whose dimensions in the model are torch.Size([9, 1024]) and whose dimensions in the checkpoint are torch.Size([9, 1024]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"head.bias\", whose dimensions in the model are torch.Size([9]) and whose dimensions in the checkpoint are torch.Size([9]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "2021-06-11 15:22:36,308\tERROR worker.py:1056 -- Possible unhandled error from worker: \u001b[36mray::Learner.push_parameters()\u001b[39m (pid=7996, ip=192.168.0.22)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"<ipython-input-4-7598620ccee7>\", line 25, in push_parameters\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 1052, in load_state_dict\n",
      "    self.__class__.__name__, \"\\n\\t\".join(error_msgs)))\n",
      "RuntimeError: Error(s) in loading state_dict for DQN:\n",
      "\tWhile copying the parameter named \"conv1.weight\", whose dimensions in the model are torch.Size([32, 3, 8, 8]) and whose dimensions in the checkpoint are torch.Size([32, 3, 8, 8]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv1.bias\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.weight\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.bias\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.running_mean\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.running_var\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv2.weight\", whose dimensions in the model are torch.Size([64, 32, 4, 4]) and whose dimensions in the checkpoint are torch.Size([64, 32, 4, 4]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv2.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.weight\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.running_mean\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.running_var\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv3.weight\", whose dimensions in the model are torch.Size([64, 64, 3, 3]) and whose dimensions in the checkpoint are torch.Size([64, 64, 3, 3]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv3.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.weight\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.running_mean\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.running_var\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"head.weight\", whose dimensions in the model are torch.Size([9, 1024]) and whose dimensions in the checkpoint are torch.Size([9, 1024]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"head.bias\", whose dimensions in the model are torch.Size([9]) and whose dimensions in the checkpoint are torch.Size([9]), an exception occurred : ('CUDA error: unspecified launch failure',).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m MineRL agent is public, connect on port 12341 with Minecraft 1.11\n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m MineRL agent is public, connect on port 12340 with Minecraft 1.11\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m 6 episode is done\n",
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m total rewards : 3 \n",
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m actor network is updated \n",
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m actor target_network is updated\n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m 6 episode is done\n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m total rewards : 6 \n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m actor network is updated \n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m actor target_network is updated\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-06-11 15:24:10,116\tERROR worker.py:1056 -- Possible unhandled error from worker: \u001b[36mray::Learner.push_parameters()\u001b[39m (pid=7996, ip=192.168.0.22)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"<ipython-input-4-7598620ccee7>\", line 25, in push_parameters\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 1052, in load_state_dict\n",
      "    self.__class__.__name__, \"\\n\\t\".join(error_msgs)))\n",
      "RuntimeError: Error(s) in loading state_dict for DQN:\n",
      "\tWhile copying the parameter named \"conv1.weight\", whose dimensions in the model are torch.Size([32, 3, 8, 8]) and whose dimensions in the checkpoint are torch.Size([32, 3, 8, 8]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv1.bias\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.weight\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.bias\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.running_mean\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.running_var\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv2.weight\", whose dimensions in the model are torch.Size([64, 32, 4, 4]) and whose dimensions in the checkpoint are torch.Size([64, 32, 4, 4]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv2.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.weight\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.running_mean\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.running_var\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv3.weight\", whose dimensions in the model are torch.Size([64, 64, 3, 3]) and whose dimensions in the checkpoint are torch.Size([64, 64, 3, 3]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv3.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.weight\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.running_mean\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.running_var\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"head.weight\", whose dimensions in the model are torch.Size([9, 1024]) and whose dimensions in the checkpoint are torch.Size([9, 1024]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"head.bias\", whose dimensions in the model are torch.Size([9]) and whose dimensions in the checkpoint are torch.Size([9]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "2021-06-11 15:24:15,117\tERROR worker.py:1056 -- Possible unhandled error from worker: \u001b[36mray::Learner.push_parameters()\u001b[39m (pid=7996, ip=192.168.0.22)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"<ipython-input-4-7598620ccee7>\", line 25, in push_parameters\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 1052, in load_state_dict\n",
      "    self.__class__.__name__, \"\\n\\t\".join(error_msgs)))\n",
      "RuntimeError: Error(s) in loading state_dict for DQN:\n",
      "\tWhile copying the parameter named \"conv1.weight\", whose dimensions in the model are torch.Size([32, 3, 8, 8]) and whose dimensions in the checkpoint are torch.Size([32, 3, 8, 8]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv1.bias\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.weight\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.bias\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.running_mean\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.running_var\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv2.weight\", whose dimensions in the model are torch.Size([64, 32, 4, 4]) and whose dimensions in the checkpoint are torch.Size([64, 32, 4, 4]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv2.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.weight\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.running_mean\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.running_var\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv3.weight\", whose dimensions in the model are torch.Size([64, 64, 3, 3]) and whose dimensions in the checkpoint are torch.Size([64, 64, 3, 3]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv3.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.weight\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.running_mean\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.running_var\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"head.weight\", whose dimensions in the model are torch.Size([9, 1024]) and whose dimensions in the checkpoint are torch.Size([9, 1024]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"head.bias\", whose dimensions in the model are torch.Size([9]) and whose dimensions in the checkpoint are torch.Size([9]), an exception occurred : ('CUDA error: unspecified launch failure',).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m MineRL agent is public, connect on port 12341 with Minecraft 1.11\n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m MineRL agent is public, connect on port 12340 with Minecraft 1.11\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m 7 episode is done\n",
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m total rewards : 7 \n",
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m actor network is updated \n",
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m actor target_network is updated\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-06-11 15:25:57,794\tERROR worker.py:1056 -- Possible unhandled error from worker: \u001b[36mray::Learner.push_parameters()\u001b[39m (pid=7996, ip=192.168.0.22)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"<ipython-input-4-7598620ccee7>\", line 25, in push_parameters\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 1052, in load_state_dict\n",
      "    self.__class__.__name__, \"\\n\\t\".join(error_msgs)))\n",
      "RuntimeError: Error(s) in loading state_dict for DQN:\n",
      "\tWhile copying the parameter named \"conv1.weight\", whose dimensions in the model are torch.Size([32, 3, 8, 8]) and whose dimensions in the checkpoint are torch.Size([32, 3, 8, 8]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv1.bias\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.weight\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.bias\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.running_mean\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.running_var\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv2.weight\", whose dimensions in the model are torch.Size([64, 32, 4, 4]) and whose dimensions in the checkpoint are torch.Size([64, 32, 4, 4]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv2.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.weight\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.running_mean\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.running_var\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv3.weight\", whose dimensions in the model are torch.Size([64, 64, 3, 3]) and whose dimensions in the checkpoint are torch.Size([64, 64, 3, 3]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv3.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.weight\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.running_mean\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.running_var\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"head.weight\", whose dimensions in the model are torch.Size([9, 1024]) and whose dimensions in the checkpoint are torch.Size([9, 1024]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"head.bias\", whose dimensions in the model are torch.Size([9]) and whose dimensions in the checkpoint are torch.Size([9]), an exception occurred : ('CUDA error: unspecified launch failure',).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m 7 episode is done\n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m total rewards : 7 \n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m actor network is updated \n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m actor target_network is updated\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-06-11 15:26:03,693\tERROR worker.py:1056 -- Possible unhandled error from worker: \u001b[36mray::Learner.push_parameters()\u001b[39m (pid=7996, ip=192.168.0.22)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"<ipython-input-4-7598620ccee7>\", line 25, in push_parameters\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 1052, in load_state_dict\n",
      "    self.__class__.__name__, \"\\n\\t\".join(error_msgs)))\n",
      "RuntimeError: Error(s) in loading state_dict for DQN:\n",
      "\tWhile copying the parameter named \"conv1.weight\", whose dimensions in the model are torch.Size([32, 3, 8, 8]) and whose dimensions in the checkpoint are torch.Size([32, 3, 8, 8]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv1.bias\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.weight\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.bias\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.running_mean\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.running_var\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv2.weight\", whose dimensions in the model are torch.Size([64, 32, 4, 4]) and whose dimensions in the checkpoint are torch.Size([64, 32, 4, 4]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv2.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.weight\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.running_mean\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.running_var\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv3.weight\", whose dimensions in the model are torch.Size([64, 64, 3, 3]) and whose dimensions in the checkpoint are torch.Size([64, 64, 3, 3]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv3.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.weight\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.running_mean\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.running_var\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"head.weight\", whose dimensions in the model are torch.Size([9, 1024]) and whose dimensions in the checkpoint are torch.Size([9, 1024]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"head.bias\", whose dimensions in the model are torch.Size([9]) and whose dimensions in the checkpoint are torch.Size([9]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m MineRL agent is public, connect on port 12341 with Minecraft 1.11\n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m MineRL agent is public, connect on port 12340 with Minecraft 1.11\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m 8 episode is done\n",
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m total rewards : 0 \n",
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m actor network is updated \n",
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m actor target_network is updated\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-06-11 15:27:40,952\tERROR worker.py:1056 -- Possible unhandled error from worker: \u001b[36mray::Learner.push_parameters()\u001b[39m (pid=7996, ip=192.168.0.22)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"<ipython-input-4-7598620ccee7>\", line 25, in push_parameters\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 1052, in load_state_dict\n",
      "    self.__class__.__name__, \"\\n\\t\".join(error_msgs)))\n",
      "RuntimeError: Error(s) in loading state_dict for DQN:\n",
      "\tWhile copying the parameter named \"conv1.weight\", whose dimensions in the model are torch.Size([32, 3, 8, 8]) and whose dimensions in the checkpoint are torch.Size([32, 3, 8, 8]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv1.bias\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.weight\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.bias\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.running_mean\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.running_var\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv2.weight\", whose dimensions in the model are torch.Size([64, 32, 4, 4]) and whose dimensions in the checkpoint are torch.Size([64, 32, 4, 4]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv2.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.weight\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.running_mean\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.running_var\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv3.weight\", whose dimensions in the model are torch.Size([64, 64, 3, 3]) and whose dimensions in the checkpoint are torch.Size([64, 64, 3, 3]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv3.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.weight\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.running_mean\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.running_var\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"head.weight\", whose dimensions in the model are torch.Size([9, 1024]) and whose dimensions in the checkpoint are torch.Size([9, 1024]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"head.bias\", whose dimensions in the model are torch.Size([9]) and whose dimensions in the checkpoint are torch.Size([9]), an exception occurred : ('CUDA error: unspecified launch failure',).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m 8 episode is done\n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m total rewards : 8 \n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m actor network is updated \n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m actor target_network is updated\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-06-11 15:27:47,375\tERROR worker.py:1056 -- Possible unhandled error from worker: \u001b[36mray::Learner.push_parameters()\u001b[39m (pid=7996, ip=192.168.0.22)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"<ipython-input-4-7598620ccee7>\", line 25, in push_parameters\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 1052, in load_state_dict\n",
      "    self.__class__.__name__, \"\\n\\t\".join(error_msgs)))\n",
      "RuntimeError: Error(s) in loading state_dict for DQN:\n",
      "\tWhile copying the parameter named \"conv1.weight\", whose dimensions in the model are torch.Size([32, 3, 8, 8]) and whose dimensions in the checkpoint are torch.Size([32, 3, 8, 8]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv1.bias\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.weight\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.bias\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.running_mean\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.running_var\", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn1.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv2.weight\", whose dimensions in the model are torch.Size([64, 32, 4, 4]) and whose dimensions in the checkpoint are torch.Size([64, 32, 4, 4]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv2.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.weight\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.running_mean\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.running_var\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn2.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv3.weight\", whose dimensions in the model are torch.Size([64, 64, 3, 3]) and whose dimensions in the checkpoint are torch.Size([64, 64, 3, 3]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"conv3.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.weight\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.bias\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.running_mean\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.running_var\", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"bn3.num_batches_tracked\", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"head.weight\", whose dimensions in the model are torch.Size([9, 1024]) and whose dimensions in the checkpoint are torch.Size([9, 1024]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\tWhile copying the parameter named \"head.bias\", whose dimensions in the model are torch.Size([9]) and whose dimensions in the checkpoint are torch.Size([9]), an exception occurred : ('CUDA error: unspecified launch failure',).\n",
      "\u001b[2m\u001b[36m(pid=7993)\u001b[0m MineRL agent is public, connect on port 12341 with Minecraft 1.11\n",
      "\u001b[2m\u001b[36m(pid=7998)\u001b[0m MineRL agent is public, connect on port 12340 with Minecraft 1.11\n"
     ]
    }
   ],
   "source": [
    "explore = [actor.explore.remote(learner, memory) for actor in actor_list]\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "prescription-matter",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=5612)\u001b[0m started\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=5612)\u001b[0m /home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/ray/workers/default_worker.py:81: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:141.)\n",
      "\u001b[2m\u001b[36m(pid=5612)\u001b[0m   action=\"store_true\",\n"
     ]
    }
   ],
   "source": [
    "update = learner.update_network.remote(memory,batch_size, optimizer)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "induced-transfer",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "1128"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=5612)\u001b[0m Count : 10 leaner_network updated\n",
      "\u001b[2m\u001b[36m(pid=5612)\u001b[0m learner model saved\n",
      "\u001b[2m\u001b[36m(pid=5612)\u001b[0m Count : 20 leaner_network updated\n",
      "\u001b[2m\u001b[36m(pid=5612)\u001b[0m learner model saved\n",
      "\u001b[2m\u001b[36m(pid=5612)\u001b[0m Count : 30 leaner_network updated\n",
      "\u001b[2m\u001b[36m(pid=5612)\u001b[0m learner model saved\n",
      "\u001b[2m\u001b[36m(pid=5612)\u001b[0m Count : 40 leaner_network updated\n",
      "\u001b[2m\u001b[36m(pid=5612)\u001b[0m learner model saved\n",
      "\u001b[2m\u001b[36m(pid=5612)\u001b[0m Count : 50 leaner_target_network updated\n",
      "\u001b[2m\u001b[36m(pid=5612)\u001b[0m Count : 50 leaner_network updated\n",
      "\u001b[2m\u001b[36m(pid=5612)\u001b[0m learner model saved\n",
      "\u001b[2m\u001b[36m(pid=5612)\u001b[0m Count : 60 leaner_network updated\n",
      "\u001b[2m\u001b[36m(pid=5612)\u001b[0m learner model saved\n",
      "\u001b[2m\u001b[36m(pid=5612)\u001b[0m Count : 70 leaner_network updated\n",
      "\u001b[2m\u001b[36m(pid=5612)\u001b[0m learner model saved\n",
      "\u001b[2m\u001b[36m(pid=5612)\u001b[0m Count : 80 leaner_network updated\n",
      "\u001b[2m\u001b[36m(pid=5612)\u001b[0m learner model saved\n",
      "\u001b[2m\u001b[36m(pid=5612)\u001b[0m Count : 90 leaner_network updated\n",
      "\u001b[2m\u001b[36m(pid=5612)\u001b[0m learner model saved\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=5615)\u001b[0m /home/kukjin/Study/RL/softwardcapstonedesign/ApexDQFD/utils.py:101: RuntimeWarning: divide by zero encountered in power\n",
      "\u001b[2m\u001b[36m(pid=5615)\u001b[0m   is_weight = np.power(self.tree.n_entries * sampling_probabilities, -self.beta)\n",
      "\u001b[2m\u001b[36m(pid=5615)\u001b[0m /home/kukjin/Study/RL/softwardcapstonedesign/ApexDQFD/utils.py:102: RuntimeWarning: invalid value encountered in true_divide\n",
      "\u001b[2m\u001b[36m(pid=5615)\u001b[0m   is_weight /= (is_weight.max() + 1e-5)\n",
      "2021-06-10 18:01:41,322\tERROR worker.py:1056 -- Possible unhandled error from worker: \u001b[36mray::Learner.update_network()\u001b[39m (pid=5612, ip=192.168.0.22)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/kukjin/anaconda3/envs/minerl/lib/python3.7/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"<ipython-input-4-7598620ccee7>\", line 60, in update_network\n",
      "TypeError: cannot unpack non-iterable int object\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=5611)\u001b[0m 0 episode is done\n",
      "\u001b[2m\u001b[36m(pid=5611)\u001b[0m total rewards : 0 \n",
      "\u001b[2m\u001b[36m(pid=5611)\u001b[0m actor network is updated \n",
      "\u001b[2m\u001b[36m(pid=5611)\u001b[0m actor target_network is updated\n",
      "\u001b[2m\u001b[36m(pid=5613)\u001b[0m 0 episode is done\n",
      "\u001b[2m\u001b[36m(pid=5613)\u001b[0m total rewards : 0 \n",
      "\u001b[2m\u001b[36m(pid=5613)\u001b[0m actor network is updated \n",
      "\u001b[2m\u001b[36m(pid=5613)\u001b[0m actor target_network is updated\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=5611)\u001b[0m MineRL agent is public, connect on port 12341 with Minecraft 1.11\n",
      "\u001b[2m\u001b[36m(pid=5613)\u001b[0m MineRL agent is public, connect on port 12340 with Minecraft 1.11\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=5611)\u001b[0m 1 episode is done\n",
      "\u001b[2m\u001b[36m(pid=5611)\u001b[0m total rewards : 15 \n",
      "\u001b[2m\u001b[36m(pid=5611)\u001b[0m actor network is updated \n",
      "\u001b[2m\u001b[36m(pid=5611)\u001b[0m actor target_network is updated\n",
      "\u001b[2m\u001b[36m(pid=5613)\u001b[0m 1 episode is done\n",
      "\u001b[2m\u001b[36m(pid=5613)\u001b[0m total rewards : 9 \n",
      "\u001b[2m\u001b[36m(pid=5613)\u001b[0m actor network is updated \n",
      "\u001b[2m\u001b[36m(pid=5613)\u001b[0m actor target_network is updated\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=5611)\u001b[0m MineRL agent is public, connect on port 12341 with Minecraft 1.11\n",
      "\u001b[2m\u001b[36m(pid=5613)\u001b[0m MineRL agent is public, connect on port 12340 with Minecraft 1.11\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=5611)\u001b[0m 2 episode is done\n",
      "\u001b[2m\u001b[36m(pid=5611)\u001b[0m total rewards : 8 \n",
      "\u001b[2m\u001b[36m(pid=5611)\u001b[0m actor network is updated \n",
      "\u001b[2m\u001b[36m(pid=5611)\u001b[0m actor target_network is updated\n",
      "\u001b[2m\u001b[36m(pid=5613)\u001b[0m 2 episode is done\n",
      "\u001b[2m\u001b[36m(pid=5613)\u001b[0m total rewards : 0 \n",
      "\u001b[2m\u001b[36m(pid=5613)\u001b[0m actor network is updated \n",
      "\u001b[2m\u001b[36m(pid=5613)\u001b[0m actor target_network is updated\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=5611)\u001b[0m MineRL agent is public, connect on port 12341 with Minecraft 1.11\n",
      "\u001b[2m\u001b[36m(pid=5613)\u001b[0m MineRL agent is public, connect on port 12340 with Minecraft 1.11\n"
     ]
    }
   ],
   "source": [
    "ray.get(memory.size.remote())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "educated-impossible",
   "metadata": {},
   "outputs": [],
   "source": [
    "actor1.env_close.remote()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "facial-visibility",
   "metadata": {},
   "outputs": [],
   "source": [
    "actor2.env_close.remote()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "young-abuse",
   "metadata": {},
   "outputs": [],
   "source": [
    "actor3.env_close.remote()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "demanding-compact",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fabulous-writer",
   "metadata": {},
   "outputs": [],
   "source": [
    "def visualize(datapath, index, agent):\n",
    "    data = pd.read_csv(datapath)\n",
    "    plt.figure(figsize=(14, 10))\n",
    "    plt.subplot(index)\n",
    "    plt.title(\"Total Rewards : agent {}\".format(agent))\n",
    "    plt.xlabel(\"Episodes\")\n",
    "    plt.ylabel(\"Total Rewards\");\n",
    "    x = range(1, len(data['rewards'].values) + 1)\n",
    "    plt.plot(data.index, data['rewards'].values, '-b', label='rewards');"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "single-vegetation",
   "metadata": {},
   "outputs": [],
   "source": [
    "data0 = \"./trainstat_1/train_stat_minerl_agent 0.csv\"\n",
    "agent0 = 0\n",
    "index0 = 311\n",
    "\n",
    "data1 = \"./trainstat_1/train_stat_minerl_agent 1.csv\"\n",
    "agent1 = 1\n",
    "index1 = 312\n",
    "\n",
    "data2 = \"./trainstat_1/train_stat_minerl_agent 2.csv\"\n",
    "agent2 = 2\n",
    "index2 = 313\n",
    "\n",
    "visualize(data0, index0, agent0)\n",
    "visualize(data1, index1, agent1)\n",
    "visualize(data2, index2, agent2)\n",
    "\n",
    "data = pd.read_csv(\"./trainstat_1/train_stat_minerl_learner.csv\")\n",
    "plt.figure(figsize=(20, 10))\n",
    "plt.subplot(111)\n",
    "plt.title(\"loss\")\n",
    "plt.xlabel(\"steps\")\n",
    "plt.ylabel(\"Total loss\");\n",
    "x = range(1, len(data['loss'].values) + 1)\n",
    "plt.plot(data.index, data['loss'].values, '-g', label='loss');\n",
    "\n",
    "\n",
    "plt.show()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "interstate-syndication",
   "metadata": {
    "scrolled": false
   },
   "outputs": [],
   "source": [
    "data0 = \"./trainstat_2/train_stat_minerl_agent 0.csv\"\n",
    "agent0 = 0\n",
    "index0 = 311\n",
    "\n",
    "data1 = \"./trainstat_2/train_stat_minerl_agent 1.csv\"\n",
    "agent1 = 1\n",
    "index1 = 312\n",
    "\n",
    "data2 = \"./trainstat_2/train_stat_minerl_agent 2.csv\"\n",
    "agent2 = 2\n",
    "index2 = 313\n",
    "\n",
    "visualize(data0, index0, agent0)\n",
    "visualize(data1, index1, agent1)\n",
    "visualize(data2, index2, agent2)\n",
    "\n",
    "data = pd.read_csv(\"./trainstat_2/train_stat_minerl_learner.csv\")\n",
    "plt.figure(figsize=(20, 10))\n",
    "plt.subplot(111)\n",
    "plt.title(\"loss\")\n",
    "plt.xlabel(\"steps\")\n",
    "plt.ylabel(\"Total loss\");\n",
    "x = range(1, len(data['loss'].values) + 1)\n",
    "plt.plot(data.index, data['loss'].values, '-g', label='loss');\n",
    "\n",
    "\n",
    "plt.show()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cleared-spanking",
   "metadata": {},
   "outputs": [],
   "source": [
    "data0 = \"./trainstat_4/train_stat_minerl_agent 0.csv\"\n",
    "agent0 = 0\n",
    "index0 = 311\n",
    "\n",
    "data1 = \"./trainstat_4/train_stat_minerl_agent 1.csv\"\n",
    "agent1 = 1\n",
    "index1 = 312\n",
    "\n",
    "data2 = \"./trainstat_4/train_stat_minerl_agent 2.csv\"\n",
    "agent2 = 2\n",
    "index2 = 313\n",
    "\n",
    "visualize(data0, index0, agent0)\n",
    "visualize(data1, index1, agent1)\n",
    "visualize(data2, index2, agent2)\n",
    "\n",
    "plt.show()\n",
    "\n",
    "data = pd.read_csv(\"./trainstat_4/train_stat_minerl_learner.csv\")\n",
    "plt.figure(figsize=(20, 10))\n",
    "plt.subplot(111)\n",
    "plt.title(\"loss\")\n",
    "plt.xlabel(\"steps\")\n",
    "plt.ylabel(\"Total loss\");\n",
    "x = range(1, len(data['loss'].values) + 1)\n",
    "plt.plot(data.index, data['loss'].values, '-g', label='loss');\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "practical-renewal",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
