2021-05-19 22:13:59,685 INFO    MainThread:13124 [wandb_setup.py:_flush():69] setting env: {}
2021-05-19 22:13:59,685 INFO    MainThread:13124 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-19 22:13:59,685 INFO    MainThread:13124 [wandb_init.py:_log_setup():336] Logging user logs to /home/kukjin/Study/RL/소프트웨어 융합 캡스톤 디자인/ApexDQFD/wandb/run-20210519_221359-2gumah7l/logs/debug.log
2021-05-19 22:13:59,685 INFO    MainThread:13124 [wandb_init.py:_log_setup():337] Logging internal logs to /home/kukjin/Study/RL/소프트웨어 융합 캡스톤 디자인/ApexDQFD/wandb/run-20210519_221359-2gumah7l/logs/debug-internal.log
2021-05-19 22:13:59,686 INFO    MainThread:13124 [wandb_init.py:init():369] calling init triggers
2021-05-19 22:13:59,686 INFO    MainThread:13124 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-05-19 22:13:59,686 INFO    MainThread:13124 [wandb_init.py:init():418] starting backend
2021-05-19 22:13:59,686 INFO    MainThread:13124 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-19 22:13:59,688 INFO    MainThread:13124 [backend.py:ensure_launched():123] starting backend process...
2021-05-19 22:13:59,732 INFO    MainThread:13124 [backend.py:ensure_launched():128] started backend process with pid: 13972
2021-05-19 22:13:59,733 INFO    MainThread:13124 [wandb_init.py:init():423] backend started and connected
2021-05-19 22:13:59,746 INFO    MainThread:13124 [wandb_init.py:init():465] updated telemetry
2021-05-19 22:13:59,747 INFO    MainThread:13124 [wandb_init.py:init():484] communicating current version
2021-05-19 22:14:04,747 INFO    MainThread:13124 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-19 22:14:34,748 INFO    MainThread:13124 [interface.py:_communicate_run():642] couldn't get run from backend
2021-05-19 22:14:34,748 ERROR   MainThread:13124 [wandb_init.py:init():501] backend process timed out
2021-05-19 22:14:34,748 ERROR   MainThread:13124 [wandb_init.py:init():510] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2021-05-19 22:14:39,768 INFO    MainThread:13124 [wandb_init.py:teardown():187] tearing down wandb.init
